oauthClient:
  redirectUris:
    - http://localhost/oauth2/callback
    - http://localhost:4180/oauth2/callback
  applicationType: web

directions: |+2
  Okta configuration written to .env
  Add this file to .gitignore!
  Run these application with:
      docker compose up
